"""empty message

Revision ID: 35d88660acad
Revises: edb959d90df6
Create Date: 2021-10-20 13:09:10.164945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '35d88660acad'
down_revision = 'edb959d90df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tour_picture',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tour_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('location',
                  geoalchemy2.types.Geometry(geometry_type='POINT',
                                             from_text='ST_GeomFromEWKT',
                                             name='geometry'),
                  nullable=True),
        sa.Column('picture_key', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tour_id'],
            ['tour.id'],
        ), sa.PrimaryKeyConstraint('id', 'tour_id'))
    #op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('auth_name',
                  sa.VARCHAR(length=256),
                  autoincrement=False,
                  nullable=True),
        sa.Column('auth_srid',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True),
        sa.Column('srtext',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.Column('proj4text',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.CheckConstraint('(srid > 0) AND (srid <= 998999)',
                           name='spatial_ref_sys_srid_check'),
        sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey'))
    op.drop_table('tour_picture')
    # ### end Alembic commands ###
