"""empty message

Revision ID: 50b230b07e59
Revises: 1d82d23e5f48
Create Date: 2021-12-28 15:38:46.216170

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '50b230b07e59'
down_revision = '1d82d23e5f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE tour ALTER COLUMN polyline TYPE geometry(LINESTRING, 4326) USING ST_SetSRID(polyline,4326);'
    )
    op.execute(
        'ALTER TABLE tour ALTER COLUMN "centerPoint" TYPE geometry(POINT, 4326) USING ST_SetSRID("centerPoint",4326);'
    )
    op.execute(
        'ALTER TABLE tour_picture ALTER COLUMN location TYPE geometry(POINT, 4326) USING ST_SetSRID(location,4326);'
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('auth_name',
                  sa.VARCHAR(length=256),
                  autoincrement=False,
                  nullable=True),
        sa.Column('auth_srid',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True),
        sa.Column('srtext',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.Column('proj4text',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.CheckConstraint('(srid > 0) AND (srid <= 998999)',
                           name='spatial_ref_sys_srid_check'),
        sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey'))
    # ### end Alembic commands ###
