"""empty message

Revision ID: e8f7b78287d8
Revises: 35d88660acad
Create Date: 2021-10-20 14:17:24.368195

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e8f7b78287d8'
down_revision = '35d88660acad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_index('idx_tour_picture_location', table_name='tour_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tour_picture_location',
                    'tour_picture', ['location'],
                    unique=False)
    op.create_table(
        'spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('auth_name',
                  sa.VARCHAR(length=256),
                  autoincrement=False,
                  nullable=True),
        sa.Column('auth_srid',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True),
        sa.Column('srtext',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.Column('proj4text',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.CheckConstraint('(srid > 0) AND (srid <= 998999)',
                           name='spatial_ref_sys_srid_check'),
        sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey'))
    # ### end Alembic commands ###
