"""empty message

Revision ID: edb959d90df6
Revises: 1a0bc8a3688e
Create Date: 2021-10-13 11:40:52.930184

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'edb959d90df6'
down_revision = '1a0bc8a3688e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('tour', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'amount')
    op.create_table(
        'spatial_ref_sys',
        sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('auth_name',
                  sa.VARCHAR(length=256),
                  autoincrement=False,
                  nullable=True),
        sa.Column('auth_srid',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True),
        sa.Column('srtext',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.Column('proj4text',
                  sa.VARCHAR(length=2048),
                  autoincrement=False,
                  nullable=True),
        sa.CheckConstraint('(srid > 0) AND (srid <= 998999)',
                           name='spatial_ref_sys_srid_check'),
        sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey'))
    # ### end Alembic commands ###
